//LoginDetails
url=https://accounts.magicbricks.com/userauth/login
userName=6353863899@yopmail.com
pass=times@123

//Paymentdetails
Card=4111111111111111
ExpiryNo=1129
cvvNo=123

//PropertyID
id=77692281
location=Ashok Nagar, Bangalore

//DBcredential
db.url=jdbc:mysql://172.25.115.100:3311/property
db.username=apptesting_user
db.password=App123Test@r321